export const resumePageContent = {
  eyebrow: "Resume",
  title: {
    first: "Gretchen ",
    last: "Ugalde",
  },
  intro:
    "Scenic designer with professional work spanning regional theatre, graduate training, and collaborative production across new work, musicals, and classical storytelling.",
  contact: {
    emailHref: "mailto:gretch.ugalde@gmail.com",
    emailLabel: "gretch.ugalde@gmail.com",
    websiteHref: "https://www.gretchenugalde.com",
    websiteLabel: "gretchenugalde.com",
  },
  pdfHref: "/gretchen-ugalde-resume.pdf",
  scenicDesignCredits: [
    ["How I Became A Pirate", "Kari Hayter", "South Coast Repertory Theatre"],
    ["Noises Off", "Eli Simon", "University of California, Irvine"],
    ["Translating Ngugi (Co-Design with Ashley Mendez)", "S.Ama Wray", "University of California, Irvine"],
    ["The Little Mermaid", "Scott Koonce", "University of Missouri"],
    ["Baskerville: A Sherlock Holmes Mystery", "Brandon V. Riley", "University of Missouri"],
    ["Gloria", "Andrew Borba", "University of California, Irvine"],
    ["Lucky Stiff", "Brandon McShaffrey", "Maples Repertory Theatre"],
    ["The Importance of Being Earnest", "Jef Awada", "Maples Repertory Theatre"],
    ["The Bald Soprano", "Mihai Maniutiu", "University of California, Irvine"],
    ["Vanya & Sonia & Masha & Spike", "Jim Bray", "Okoboji Summer Theatre"],
    ["Promises, Promises", "Bernie Monroe", "Okoboji Summer Theatre"],
    ["Side by Side by Sondheim", "Bernie Monroe", "Conservatory for the Performing Arts"],
    ["Painting Churches", "Courtney Crouse", "Okoboji Summer Theatre"],
    ["A Comedy of Tenors", "Stephens Brotebeck", "Okoboji Summer Theatre"],
    ["9 to 5", "Bernie Monroe", "Conservatory for the Performing Arts"],
    ["Ripcord", "Peter Reynolds", "Maples Repertory Theatre"],
    ["Gods of Comedy", "Stephen Brotebeck", "Okoboji Summer Theatre"],
    ["Grease", "Stephen Brotebeck", "Okoboji Summer Theatre"],
    ["Living Out", "Jane Page", "University of California, Irvine"],
    ["Tea", "Kelley Ho", "University of California, Irvine"],
    ["Love's Labour's Lost", "Andrew Borba", "University of California, Irvine"],
  ],
  assistantCredits: [
    ["Hamlet (Scenic Apprentice)", "Clint Ramos", "Mark Taper Forum"],
    ["South Pacific", "Arnel Sancianco", "The Muny"],
    ["A Chorus Line", "Miguel Urbino", "Samsung Performing Arts, TGA Manila"],
    ["Shrek (Associate)", "Efren Delgadillo Jr.", "Oregon Shakespeare Festival"],
    ["Comedy of Errors (Associate)", "Efren Delgadillo Jr.", "Oregon Shakespeare Festival"],
    ["The Merry Wives of Windsor (Associate)", "Efren Delgadillo Jr.", "Oregon Shakespeare Festival"],
    ["Much Ado About Nothing (Associate)", "Efren Delgadillo Jr.", "Oregon Shakespeare Festival"],
    ["Jane Eyre (Associate)", "Efren Delgadillo Jr.", "Oregon Shakespeare Festival"],
    ["9 to 5 (Associate)", "Brandon PT Davis", "University of Missouri"],
    ["The Importance of Being Earnest", "Leah Ramillano", "University of California, Irvine"],
    ["Company", "Brandon PT Davis", "University of California, Irvine"],
    ["Refugee Hotel", "Fernando Penaloza", "University of California, Irvine"],
    ["Legally Blonde", "Tyler Scrivner", "University of California, Irvine"],
  ],
  education: [
    {
      year: "2026",
      degree: "Master of Fine Arts in Scenic Design",
      school: "University of California, Irvine",
    },
    {
      year: "2019",
      degree: "Bachelor of Arts in Drama, Emphasis in Scenic Design",
      school: "University of California, Irvine",
    },
  ],
} as const;
